config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :letters
  resources :saved_letters
  resources :today_letters
  resources :today_sentences
  get '/admini', to: 'admin#index'
  get '/my_letters', to: 'letters#my_letters'
  get '/about', to: 'about#index'
  get '/info', to: 'about#info'
  get '/menu', to: 'timeline#index'
  root 'letters#index'
  post '/likes', to: 'likes#create'

   # error pages
   %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    
    if user.has_role? :admin
      can :manage, :all #create, edit 등
    # 일반 유저 권한
    else
      can [:index, :show, :new, :create], Letter
      can [:edit, :update, :destroy], Letter, user_id: user.id
      can :destroy, Letter, user_id: user.id
    end
 
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/declaration.rb
class Declaration < ApplicationRecord
end

app/models/letter.rb
class Letter < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy, foreign_key: 'letter_id', :counter_cache => :likes_count
  has_many :saved_letter, dependent: :destroy
  has_one :today_letter, dependent: :destroy
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user, foreign_key: 'user_id'
    belongs_to :letter, foreign_key: 'letter_id', counter_cache: true
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/saved_letter.rb
class SavedLetter < ApplicationRecord
    belongs_to :user
end

app/models/today_letter.rb
class TodayLetter < ApplicationRecord
end

app/models/today_sentence.rb
class TodaySentence < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :assign_default_role
  def assign_default_role
    add_role(:humen)
  end
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :likes, dependent: :destroy
  has_many :letters, dependent: :destroy, foreign_key: 'user_id'
  has_many :saved_letters, dependent: :destroy
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
    def info
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    def index
        authorize! :manage, @Letter
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_helper.rb
module ErrorHelper
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/saved_letter_helper.rb
module SavedLetterHelper
end

app/helpers/timeline_helper.rb
module TimelineHelper
end

app/views/admin/index.html.haml
%h1 관리자 페이지
%br
.menu-options
    = link_to "오늘의 문장 목록", today_sentences_path
    = link_to "오늘의 문장 추가하기", new_today_sentence_path
    = link_to "오늘의 편지 목록", today_letters_path
    = link_to "오늘의 편지 추가하기", new_today_letter_path

app/views/layouts/_navigation_bar.html.haml
.navigation-bar
  .menu
    = link_to image_tag("buttons/x@3x.png", class: "btn-menu-close"), :back if current_page?(menu_path)
    - if defined?(resource) and current_page?(new_user_registration_path(resource))
      = link_to image_tag("buttons/x@3x.png", class: "btn-menu-close"), :back 
    - else
      = link_to image_tag("buttons/menu@3x.png", class: "btn-menu"), menu_path unless current_page?(menu_path)
  -# .refresh
  = link_to '글쓰기', new_letter_path, class: "refresh btn-new-letter" if current_page?(letters_path) or current_page?(root_path)
  = link_to image_tag("buttons/back@3x.png", class: "refresh btn-refresh"), :back if params[:id].present? and current_page?(letter_path)

  .name
    = "다른 칭찬" if current_page?(letters_path) or current_page?(root_path)
    = "내게 칭찬쓰기" if current_page?(new_letter_path)
    = "내게 쓴 칭찬" if current_page?(my_letters_path)
    = "저장한 칭찬" if current_page?(saved_letters_path)
    = "오늘의 칭찬" if current_page?(today_letters_path)
    = "정보" if current_page?(about_path)
    

app/views/layouts/application.html.haml
!!!
%html
  %head
    %meta{:content => "text/html; charset=UTF-8", "http-equiv" => "Content-Type"}/
    %title 헤아림 - 나를 위해 쓰는 편지
    = csrf_meta_tags
    = csp_meta_tag
    = stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload'
    = javascript_pack_tag 'application', 'data-turbolinks-track': 'reload'
    = favicon_link_tag asset_path('favicon.png')
    %meta{:name => 'description', :content => "헤아림은 스스로에게 편지를 쓰는 서비스입니다. 세상 누구나 마음이 힘들고, 위로와 격려가 필요합니다. ‘헤아림’ 은 자신과 좋은 친구가 되는 것을 도와 드립니다."}/
    %meta{:name => 'keywords', :content => "편지, 나에게, 치유, 정신건강"}/
    %meta{:charset => "utf-8"}/
    %meta{:content => "IE=edge", "http-equiv" => "X-UA-Compatible"}/
    %meta{:content => "width=device-width, initial-scale=1.0, maximum-scale=1.0, user-scalable=0", :name => "viewport"}/
    %meta{:property => "og:title", :content => "헤아림 - 나를 위해 쓰는 편지" }
    %meta{:property => "og:description", :content => "헤아림은 스스로에게 편지를 쓰는 서비스입니다. 세상 누구나 마음이 힘들고, 위로와 격려가 필요합니다. ‘헤아림’ 은 자신과 좋은 친구가 되는 것을 도와 드립니다." }
    %meta{:property => "og:image", :content => image_url("hearim.png") }
    / Naver 
    %meta{:name => "naver-site-verification", :content => "8c72b94136c7d4f2e7e07ce9f8307cbf10ca62a5"}
    / Global site tag (gtag.js) - Google Analytics
    %script{:async => "", :src => "https://www.googletagmanager.com/gtag/js?id=UA-142489546-1"}
    %script
      window.dataLayer = window.dataLayer || [];
      function gtag(){dataLayer.push(arguments);}
      gtag('js', new Date());
      gtag('config', 'UA-142489546-1');

  %body
    = render "layouts/navigation_bar"
    .page-container
      = yield

app/views/layouts/menu.html.haml
.menu-options
    = link_to '내게 편지쓰기', new_letter_path if current_user.present?
    = link_to '공개된 편지', letters_path
    = link_to '내게 쓴 편지함', saved_letters_path if current_user.present?
    = link_to '저장된 편지', saved_letters_path if current_user.present?
    = link_to '오늘의 편지', today_letters_path
    = link_to '정보', about_path
    - if user_signed_in?
        = link_to '로그아웃', destroy_user_session_path, method: :delete
    - else
        = link_to '로그인', new_user_session_path
        = link_to '회원가입', new_user_registration_path