config/routes.rb
Rails.application.routes.draw do
  mount RailsAdmin::Engine => '/admin', as: 'rails_admin'
  devise_for :users
  resources :letters
  resources :saved_letters
  resources :today_letters
  resources :today_sentences
  get '/admini', to: 'admin#index'
  get '/my_letters', to: 'letters#my_letters'
  get '/about', to: 'about#index'
  get '/info', to: 'about#info'
  get '/menu', to: 'timeline#index'
  root 'letters#index'
  post '/likes', to: 'likes#create'

   # error pages
   %w( 404 422 500 503 ).each do |code|
    get code, :to => "errors#show", :code => code
  end
end

app/models/ability.rb
# frozen_string_literal: true

class Ability
  include CanCan::Ability

  def initialize(user)
    user ||= User.new
    
    if user.has_role? :admin
      can :manage, :all #create, edit 등
    # 일반 유저 권한
    else
      can [:index, :show, :new, :create], Letter
      can [:edit, :update, :destroy], Letter, user_id: user.id
      can :destroy, Letter, user_id: user.id
    end
 
    # Define abilities for the passed in user here. For example:
    #
    #   user ||= User.new # guest user (not logged in)
    #   if user.admin?
    #     can :manage, :all
    #   else
    #     can :read, :all
    #   end
    #
    # The first argument to `can` is the action you are giving the user
    # permission to do.
    # If you pass :manage it will apply to every action. Other common actions
    # here are :read, :create, :update and :destroy.
    #
    # The second argument is the resource the user can perform the action on.
    # If you pass :all it will apply to every resource. Otherwise pass a Ruby
    # class of the resource.
    #
    # The third argument is an optional hash of conditions to further filter the
    # objects.
    # For example, here the user can only update published articles.
    #
    #   can :update, Article, :published => true
    #
    # See the wiki for details:
    # https://github.com/CanCanCommunity/cancancan/wiki/Defining-Abilities
  end
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  self.abstract_class = true
end

app/models/declaration.rb
class Declaration < ApplicationRecord
end

app/models/letter.rb
class Letter < ApplicationRecord
  belongs_to :user
  has_many :likes, dependent: :destroy, foreign_key: 'letter_id', :counter_cache => :likes_count
  has_many :saved_letter, dependent: :destroy
  has_one :today_letter, dependent: :destroy
end

app/models/like.rb
class Like < ApplicationRecord
    belongs_to :user, foreign_key: 'user_id'
    belongs_to :letter, foreign_key: 'letter_id', counter_cache: true
end

app/models/role.rb
class Role < ApplicationRecord
has_and_belongs_to_many :users, :join_table => :users_roles


belongs_to :resource,
           :polymorphic => true,
           :optional => true


validates :resource_type,
          :inclusion => { :in => Rolify.resource_types },
          :allow_nil => true

scopify
end

app/models/saved_letter.rb
class SavedLetter < ApplicationRecord
    belongs_to :user
end

app/models/today_letter.rb
class TodayLetter < ApplicationRecord
end

app/models/today_sentence.rb
class TodaySentence < ApplicationRecord
end

app/models/user.rb
class User < ApplicationRecord
  rolify
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable, :trackable and :omniauthable
  after_create :assign_default_role
  def assign_default_role
    add_role(:humen)
  end
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :validatable
  has_many :likes, dependent: :destroy
  has_many :letters, dependent: :destroy, foreign_key: 'user_id'
  has_many :saved_letters, dependent: :destroy
end

app/controllers/about_controller.rb
class AboutController < ApplicationController
    def index
    end
    def info
    end
end

app/controllers/admin_controller.rb
class AdminController < ApplicationController
    def index
        authorize! :manage, @Letter
    end
end

app/controllers/error_controller.rb
class ErrorController < ApplicationController
    def show
    end
end

app/controllers/likes_controller.rb
class LikesController < ApplicationController
  def index
  end

  def create
    unless current_user.present?
      redirect_to user_session_path
      return
    end

    liked = Like.find_by(user_id: current_user.id, letter_id: params[:letter])
    @letter = Letter.find_by(id: params[:letter])
    if liked.present?
      liked.destroy
      return
    end

    like = Like.new
    like.user_id = current_user.id
    like.letter_id = params[:letter]
    like.save
  end

  def destroy
    @like.destroy
  end
end

app/controllers/saved_letters_controller.rb
class SavedLettersController < ApplicationController
    def index
        @saved_letters = Letter.where(id: current_user.saved_letters.all.pluck(:letter_id)).order(created_at: :desc)
    end
    def create
        unless current_user.present?
          redirect_to user_session_path
          return
        end
        saved = SavedLetter.find_by(user_id: current_user.id, letter_id: params[:letter])
        @letter = Letter.find_by(id: params[:letter])
        if saved.present?
          saved.destroy
          return
        end

        save = SavedLetter.new
        save.user_id = current_user.id
        save.letter_id = params[:letter]
        save.save
    end
    def destroy
        @save.destroy
    end
end

app/helpers/about_helper.rb
module AboutHelper
end

app/helpers/admin_helper.rb
module AdminHelper
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/error_helper.rb
module ErrorHelper
end

app/helpers/letters_helper.rb
module LettersHelper
end

app/helpers/like_helper.rb
module LikeHelper
end

app/helpers/saved_letter_helper.rb
module SavedLetterHelper
end

app/helpers/timeline_helper.rb
module TimelineHelper
end

app/views/saved_letter/index.html.haml
%h1 Listing letters

%table
  %thead
    %tr
      %th Body
      %th 상세보기
      %th User
      %th Function

  %tbody
    - @saved_letters.each do |letter|
      %tr
        %td= letter.body
        %td= link_to 'Show', letter
        %td= current_user.email
        %td= link_to 'Edit', edit_letter_path(letter)
        %td= link_to 'Destroy', letter, method: :delete, data: { confirm: 'Are you sure?' } if can? :edit, letter

%br

= link_to 'New Letter', new_letter_path
= link_to 'Home', root_path

app/views/saved_letters/_button.html.haml
- if current_user.present? and current_user.saved_letters.pluck(:letter_id).include?(letter.id)
    = link_to image_tag("buttons/saved@3x.png", class: "btn-save"), saved_letters_path(letter: letter), remote: true, method: :post, class: "btn", id: 'js-save-touch-' + letter.id.to_s, "data-turbolinks": "false"
- else
    = link_to image_tag("buttons/fill-35@3x.png", class: "btn-save"), saved_letters_path(letter: letter), remote: true, method: :post, class: "btn", id: 'js-save-touch-' + letter.id.to_s, "data-turbolinks": "false"

app/views/saved_letters/create.js.erb
var x = $('#js-save-touch-<%= @letter.id %>'); 
$('#js-save-touch-<%= @letter.id %>').replaceWith("<%= j render partial: 'saved_letters/button', locals: {letter: @letter} %>");

app/views/saved_letters/index.html.haml
.letters
  - @saved_letters.each do |letter|
    .letter-cover
      .box
        = link_to letter, class: "letter-link" do
          .body
            .stamp
            .date
              = letter.created_at.strftime('%Y/%m/%d')
            .text
              = letter.body